---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
notifications:
  email: false
script:
  - 'bundle exec rake rubocop spec'
bundler_args: --without system_tests
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.5.0
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.4
      env: TEST_VAGRANT_VERSION=v2.2.2
    - rvm: 2.5.0
      env: TEST_VAGRANT_VERSION=HEAD
